spring:
  application:
    name: pope-api
  sql:
    init:
      mode: embedded
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.generate_statistics: true
  datasource:
    url: jdbc:mysql://localhost:3306/papas_db
    username: papas_user
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
