INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (1, 'Pedro Petrus', '30 a c. 67', 'Betsaida, Galileia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (2, 'Lino Linus', 'c. 67 a c. 76', 'Tuscia, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (3, 'Anacleto Anacletus', 'c. 76 a c. 88', 'Atenas, Grécia');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (4, 'Clemente I Clemens', '88 a 97 [nota 3]', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (5, 'Evaristo Evaristus', '97 a 105', 'Belém, Judeia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (6, 'Alexandre I Alexander', '105 a 116', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (7, 'Sisto I Xystus', '116 a 125', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (8, 'Telésforo Telesphorus', '125 a 138', 'Atenas, Acaia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (9, 'Higino Hyginus', '138 a 142', 'Atenas, Acaia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (10, 'Pio I Pius', '142 a 155', 'Aquileia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (11, 'Aniceto Anicetus', '155 a 166', 'Emersa, Síria, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (12, 'Sotero Soterius', '166 a 175', 'Fondi, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (13, 'Eleutério Eleutherius', '175 a 189', 'Nicópolis, Épiro, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (14, 'Vítor I Victor', '189 a 199', 'África, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (15, 'Zeferino Zephyrinus', '199 a 20 de dezembro de 217', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (16, 'Calixto I Callistus', '217 a 223', 'Península Ibérica, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (17, 'Urbano I Urbanus', '223 a 230', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (18, 'Ponciano Pontianus', '21 de julho de 230 a 28 de setembro de 235', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (19, 'Antero Anterus', '21 de novembro de 235 a 3 de janeiro de 236', 'Petilia Policasto, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (20, 'Fabiano Fabianus', '10 de janeiro de 236 a 20 de janeiro de 250', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (21, 'Cornélio Cornelius', '6 de março de 251 a junho de 253', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (22, 'Lúcio I Lucius', '25 de junho de 253 a 5 de março de 254', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (23, 'Estêvão I Stephanus', '12 de maio de 254 a 2 de agosto de 257', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (24, 'Sisto II Xystus Secundus', '31 de agosto de 257 a 6 de agosto de 258', 'Grécia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (25, 'Dionísio Dionysius', '22 de julho de 259 a 26 de dezembro de 268', 'Grécia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (26, 'Félix I Felix', '5 de janeiro de 269 a 30 de dezembro de 274', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (27, 'Eutiquiano Eutychianus', '4 de janeiro de 275 a 7 de dezembro de 283', 'Luni, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (28, 'Caio Caius', '17 de dezembro de 283 a 22 de abril de 296', 'Salona, Dalmácia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (29, 'Marcelino Marcellinus', '30 de junho de 296 a 24 ou 25 de outubro de 304', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (30, 'Marcelo I Marcellus', '27 de maio de 308 a 16 de janeiro de 309', 'Desconhecido');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (31, 'Eusébio Eusebius', '18 de abril de 309 (ou 310) a 17 de agosto de 309 (ou 310)', 'Sardenha, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (32, 'Melquíades Miltiades', '2 de julho de 311 a 10 de janeiro de 314', 'África Protoconsular ,Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (33, 'Silvestre I Silvester', '31 de janeiro de 314 a 31 de dezembro de 335', 'Sant''Angelo a Scala, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (34, 'Marcos Marcus', '18 de janeiro de 336 a 7 de outubro de 336', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (35, 'Júlio I Iulius', '6 de fevereiro de 337 a 12 de abril de 352', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (36, 'Libério Liberius', '17 de maio de 352 a 24 de setembro de 366', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (37, 'Dâmaso I Damasus', '1 de outubro de 366 a 11 de dezembro de 384', 'Egitânia, Lusitânia, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (38, 'Sirício Siricius', '11 de dezembro de 384 a 26 de novembro de 399', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (39, 'Anastácio I Anastasius', '26 de novembro de 399 a 19 de dezembro de 401', 'Desconhecido');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (40, 'Inocêncio I Innocentius', '22 de dezembro de 401 a 12 de março de 417', 'Albano Laziale, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (41, 'Zósimo Zosimus', '18 de março de 417 a 26 de dezembro de 418', 'Misoraca, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (42, 'Bonifácio I Bonifacius', '29 de dezembro de 418 a 4 de setembro de 422', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (43, 'Celestino I Coelestinus', '10 de setembro de 422 a 27 de julho de 432', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (44, 'Sisto III Xystus Tertius', '31 de julho de 432 a agosto de 440', 'Roma, Itália, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (45, 'Leão I Leo Magnus', '29 de setembro de 440 a 10 de novembro de 461', 'Atual Toscana, Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (46, 'Hilário Hilarius', '19 de novembro de 461 a 29 de fevereiro de 468', 'Sardenha, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (47, 'Simplício Simplicius', '3 de março de 468 a 10 de março de 483', 'Tívoli, Itália, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (48, 'Félix III (II) Felix Tertius (Secundus)', '13 de março de 483 a 1 de março de 492', 'Roma, Itália, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (49, 'Gelásio I Gelasius', '1 de março de 492 a 21 de novembro de 496', 'Mauritânia, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (50, 'Anastácio II Anastasius Secundus', '24 de novembro de 496 a 19 de novembro de 498', 'Roma, Itália, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (51, 'Símaco Symmachus', '22 de novembro de 498 a 19 de julho de 514', 'Sardenha, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (52, 'Hormisda Hormisdus', '20 de julho de 514 a 19 de julho de 523', 'Frosinone, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (53, 'João I Ioannes', '13 de agosto de 523 a 18 de maio de 526', 'Toscana, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (54, 'Félix IV (III) Felix Quartus (Tertius)', '13 de julho de 526 a 22 de setembro de 530', 'Sâmnio, Império Ocidental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (55, 'Bonifácio II Bonifacius Secundus', '22 de setembro de 530 a 17 de outubro de 532', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (56, 'João II Ioannes Secundus', '2 de janeiro de 533 a 8 de maio de 535', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (57, 'Agapito I Agapetus', '13 de maio de 535 a 22 de abril de 536', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (58, 'Silvério Silverius', '1 de junho de 536 a março de 537', 'Frosinone, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (59, 'Vigílio Vigilius', '29 de março de 537 a 7 de junho de 555', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (60, 'Pelágio I Pelagius', '16 de abril de 556 a 4 de março de 561', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (61, 'João III Ioannes Tertius', '17 de julho de 561 a 13 de julho de 574', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (62, 'Bento I Benedictus', '2 de junho de 575 a 30 de julho de 579', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (63, 'Pelágio II Pelagius Secundus', '26 de novembro de 579 a 7 de fevereiro de 590', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (64, 'Gregório I, O.S.B. Gregorius Magnus', '3 de setembro de 590 a 12 de março de 604', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (65, 'Sabiniano Sabinianus', '13 de setembro de 604 a 22 de fevereiro de 606', 'Blera, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (66, 'Bonifácio III Bonifacius Tertius', '19 de fevereiro de 607 a 12 de novembro de 607', 'Roma, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (67, 'Bonifácio IV, O.S.B. Bonifacius Quartus', '25 de agosto de 608 a 8 de maio de 615', 'Marsi, Reino Visigótico');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (68, 'Adeodato I Adeodatus', '19 de outubro de 615 a 8 de novembro de 618', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (69, 'Bonifácio V Bonifacius Quintus', '23 de novembro de 619 a 25 de outubro de 625', 'Nápoles, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (70, 'Honório I Honorius', '27 de outubro de 625 a 12 de outubro de 638', 'Campânia, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (71, 'Severino Severinus', '28 de maio de 640 a 2 de agosto de 640', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (72, 'João IV Ioannes Quartus', '24 de dezembro de 640 a 12 de outubro de 642', 'Zadar, Dalmácia, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (73, 'Teodoro I Theodorus', '24 de novembro de 642 a 14 de maio de 649', 'Palestina, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (74, 'Martinho I Martinus', '21 de julho de 649 a 16 de setembro de 655', 'Perto de Todi, Úmbria, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (75, 'Eugénio I Eugenius', '10 de agosto de 654 a 2 de junho de 657', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (76, 'Vitaliano Vitalianus', '30 de julho de 657 a 27 de janeiro de 672', 'Segni, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (77, 'Adeodato II, O.S.B. Adeodatus Secundus', '11 de abril de 672 a 17 de junho de 676', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (78, 'Dono Donus', '2 de novembro de 676 a 11 de abril de 678', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (79, 'Agatão Agatho', '27 de junho de 678 a 10 de janeiro de 681', 'Sicília, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (80, 'Leão II Leo Secundus', '17 de agosto de 682 a 28 de junho de 683', 'Sicília, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (81, 'Bento II Benedictus Secundus', '26 de junho de 684 a 8 de maio de 685', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (82, 'João V Ioannes Quintus', '23 de julho de 685 a 2 de agosto de 686', 'Síria, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (83, 'Cónon Conon', '21 de outubro de 686 a 21 de setembro de 687', 'Sicília, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (84, 'Sérgio I Sergius', '15 de dezembro de 687 a 8 de setembro de 701', 'Sicília, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (85, 'João VI Ioannes Sextus', '30 de outubro de 701 a 11 de janeiro de 705', 'Grécia, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (86, 'João VII Ioannes Septimus', '1 de março de 705 a 18 de outubro de 707', 'Rossano, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (87, 'Sisínio Sisinnius', '15 de janeiro de 708 a 4 de fevereiro de 708', 'Síria, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (88, 'Constantino Constantinus', '25 de março de 708 a 9 de abril de 715', 'Síria, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (89, 'Gregório II Gregorius Secundus', '19 de maio de 715 a 11 de fevereiro de 731', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (90, 'Gregório III Gregorius Tertius', '18 de março de 731 a novembro ou dezembro de 741', 'Síria, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (91, 'Zacarias Zacharias', '3 de dezembro de 741 a 22 de março de 752', 'Santa Severina, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (92, 'Estêvão II (III) Stephanus Secundus (Tertius)', '26 de março de 752 a 26 de abril de 757', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (93, 'Paulo I Paulus', '29 de maio de 757 a 28 de junho de 767', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (94, 'Estêvão III (IV) Stephanus Tertius (Quartus)', '7 de agosto de 767 a 24 de janeiro de 772', 'Sicília, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (95, 'Adriano I Hadrianus', '1 de fevereiro de 772 a 26 de dezembro de 795', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (96, 'Leão III Leo Tertius', '26 de dezembro de 795 a 12 de junho de 816', 'Roma, Império Bizantino');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (97, 'Estêvão IV (V) Stephanus Quartus (Quintus)', '12 de junho de 816 a 24 de janeiro de 817', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (98, 'Pascoal I Paschalis', '25 de janeiro de 817 a 11 de fevereiro de 824', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (99, 'Eugénio II Eugenius Secundus', '8 de maio de 824 a agosto de 827', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (100, 'Valentino Valentinus', 'agosto de 827 a setembro de 827', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (101, 'Gregório IV Gregorius Quartus', 'dezembro de 827 a janeiro de 844', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (102, 'Sérgio II Sergius Secundus', '25 de janeiro de 844 a 7 de janeiro de 847', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (103, 'Leão IV, O.S.B. Leo Quartus', 'janeiro de 847 a 17 de julho de 855', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (104, 'Bento III Benedictus Tertius', '29 de setembro de 855 a 17 de abril de 858', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (105, 'Nicolau I Nicolaus Magnus', '24 de abril de 858 a 13 de novembro de 867', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (106, 'Adriano II Hadrianus Secundus', '14 de dezembro de 867 a 14 de dezembro de 872', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (107, 'João VIII Ioannes Octavus', '14 de dezembro de 872 a 16 de dezembro de 882', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (108, 'Marinho I Marinus', '16 de dezembro de 882 a 15 de maio de 884', 'Gallese, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (109, 'Adriano III Hadrianus Tertius', '17 de maio de 884 a setembro de 885', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (110, 'Estêvão V (VI) Stephanus Quintus (Sextus)', '885 a 14 de setembro de 891', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (111, 'Formoso Formosus', '19 de setembro de 891 a 4 de abril de 896', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (112, 'Bonifácio VI Bonifacius Sextus', '4 de abril de 896 a 19 de abril de 896', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (113, 'Estêvão VI (VII) Stephanus Sextus (Septimus)', '22 de abril de 896 a agosto de 897', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (114, 'Romano Romanus', 'agosto de 897 a novembro de 897', 'Gallese, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (115, 'Teodoro II Theodorus Secundus', 'dezembro de 897 a dezembro de 897', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (116, 'João IX, O.S.B. Ioannes Nonus', 'janeiro de 898 a janeiro de 900', 'Tivoli, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (117, 'Bento IV Benedictus Quartus', '900 a 903', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (118, 'Leão V Leo Quintus', 'julho de 903 a setembro de 903', 'Árdea, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (119, 'Sérgio III Sergius Tertius', '29 de janeiro de 904 a 14 de abril de 911', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (120, 'Anastácio III Anastasius Tertius', 'abril de 911 a junho de 913', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (121, 'Lando Lando', 'agosto de 913 a março de 914', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (122, 'João X Ioannes Decimus', 'março de 914 a Maio de 928', 'Romanha, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (123, 'Leão VI Leo Sextus', 'Maio de 928 a dezembro de 928', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (124, 'Estêvão VII (VIII) Stephanus Septimus (Octavus)', 'dezembro de 928 a fevereiro de 931', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (125, 'João XI Ioannes Undecimus', 'março de 931 a dezembro de 935', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (126, 'Leão VII, O.S.B. Leo Septimus', '3 de janeiro de 936 a 13 de julho de 939', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (127, 'Estêvão VIII (IX) Stephanus Octavus (Nonus)', '13 de julho de 939 a outubro de 942', 'Frância Oriental');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (128, 'Marinho II Marinus Secundus', '30 de outubro de 942 a Maio de 946', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (129, 'Agapito II Agapetus Secundus', '10 de maio de 946 a dezembro de 955', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (130, 'João XII Ioannes Duodecimus', '16 de dezembro de 955 a 14 de maio de 964', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (131, 'Bento V Benedictus Quintus', '22 de maio de 964 a 23 de junho de 964', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (132, 'Leão VIII Leo Octavus', 'julho de 964 a 1 de março de 965', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (133, 'João XIII Ioannes Tertius Decimus', '1 de outubro de 965 a 6 de setembro de 972', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (134, 'Bento VI Benedictus Sextus', '19 de janeiro de 973 a junho de 974', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (135, 'Bento VII Benedictus Septimus', 'outubro de 974 a 10 de julho de 983', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (136, 'João XIV Ioannes Quartus Decimus', 'dezembro de 983 a 20 de agosto de 984', 'Pavia, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (137, 'João XV Ioannes Quintus Decimus', 'agosto de 985 a março de 996', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (138, 'Gregório V Gregorius Quintus', '3 de maio de 996 a 18 de fevereiro de 999', 'Saxônia, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (139, 'Silvestre II, O.S.B. Silvester Secundus', '2 de abril de 999 a 12 de maio de 1003', 'Auvernia, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (140, 'João XVII Ioannes Septimus Decimus', '16 de maio de 1003 a 6 de novembro de 1003', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (141, 'João XVIII Ioannes Duodevicesimus', '25 de dezembro de 1003 a 31 de julho de 1009', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (142, 'Sérgio IV, O.S.B. Sergius Quartus', '31 de julho de 1009 a 12 de maio de 1012', 'Rapagnano, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (143, 'Bento VIII Bendedictus Octavus', '18 de maio de 1012 a 9 de abril de 1024', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (144, 'João XIX Ioannes Undevicesimus', '9 de abril de 1024 a 20 de outubro de 1032', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (145, 'Bento IX Benedictus Nonus', '1 de agosto de 1032 a 16 de janeiro de 1045', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (146, 'Silvestre III Silvester Tertius', '20 de janeiro de 1045 a 10 de abril de 1045', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (147, 'Bento IX Benedictus Nonus', '10 de abril de 1045 a 1 de maio de 1045', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (148, 'Gregório VI Gregorius Sextus', '1 de maio de 1045 a 20 de dezembro de 1046', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (149, 'Clemente II Clemens Secundus', '20 de dezembro de 1046 a 9 de outubro de 1047', 'Hornburg, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (150, 'Bento IX Benedictus Nonus', '9 de outubro de 1047 a 17 de julho de 1048', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (151, 'Dâmaso II Damasus Secundus', '17 de julho de 1048 a 9 de agosto de 1048', 'Pildenau, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (152, 'Leão IX Leo Nonus', '12 de fevereiro de 1049 a 19 de abril de 1054', 'Eguischeim, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (153, 'Vítor II Victor Secundus', '13 de abril de 1055 a 28 de julho de 1057', 'Baviera, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (154, 'Estêvão IX (X), O.S.B. Stephanus Nonus (Decimus)', '2 de agosto de 1057 a 29 de março de 1058', 'Lorena, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (155, 'Nicolau II Nicolaus Secundus', '6 de dezembro de 1058 a 27 de julho de 1061', 'Mercury, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (156, 'Alexandre II Alexander Secundus', '30 de setembro de 1061 a 21 de abril de 1073', 'Milão, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (157, 'Gregório VII, O.S.B. Gregorius Septimus', '22 de abril de 1073 a 25 de maio de 1085', 'Sovana, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (158, 'Vítor III, O.S.B. Victor Tertius', '24 de maio de 1086 a 16 de setembro de 1087', 'Benevento, Ducado de Benevento');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (159, 'Urbano II, O.S.B. Urbanus Secundus', '12 de março de 1088 a 29 de julho de 1099', 'Lagery, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (160, 'Pascoal II, O.S.B.Cam. Paschalis Secundus', '13 de agosto de 1099 a 21 de janeiro de 1118', 'Santa Sofia, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (161, 'Gelásio II, O.S.B. Gelasius Secundus', '24 de janeiro de 1118 a 28 de janeiro de 1119', 'Gaeta, Principado de Cápua');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (162, 'Calisto II Callistus Secundus', '2 de fevereiro de 1119 a 13 de dezembro de 1124', 'Quingey, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (163, 'Honório II, O.S.A. Honorius Secundus', '15 de dezembro de 1124 a 13 de fevereiro de 1130', 'Casalfiumanese, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (164, 'Inocêncio II Innocentius Secundus', '14 de fevereiro de 1130 a 24 de setembro de 1143', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (165, 'Celestino II Coelestinus Secundus', '26 de setembro de 1143 a 8 de março de 1144', 'Città di Castello, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (166, 'Lúcio II , O.S.A. Lucius Secundus', '12 de março de 1144 a 15 de fevereiro de 1145', 'Bolonha, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (167, 'Eugénio III, O.Cist Eugenius Tertius', '15 de fevereiro de 1145 a 8 de julho de 1153', 'Pisa, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (168, 'Anastácio IV Anastacius Quartus', '8 de julho de 1153 a 3 de dezembro de 1154', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (169, 'Adriano IV, O.S.A. Hadrianus Quartus', '4 de dezembro de 1154 a 1 de setembro de 1159', 'Hertfordshire, Inglaterra');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (170, 'Alexandre III Alexander Tertius', '7 de setembro de 1159 a 30 de agosto de 1181', 'Siena, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (171, 'Lúcio III, O.Cist. Lucius Tertius', '1 de setembro de 1181 a 25 de novembro de 1185', 'Luca, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (172, 'Urbano III Urbanus Tertius', '25 de novembro de 1185 a 19 de outubro de 1187', 'Cuggiono, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (173, 'Gregório VIII, O.Præm Gregorius Octavus', '21 de outubro de 1187 a 17 de dezembro de 1187', 'Benevento, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (174, 'Clemente III Clemens Tertius', '17 de dezembro de 1187 a 20 de março de 1191', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (175, 'Celestino III Coelestinus Tertius', '21 de março de 1191 a 8 de janeiro de 1198', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (176, 'Inocêncio III Innocentius Tertius', '8 de janeiro de 1198 a 16 de julho de 1216', 'Gavignano, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (177, 'Honório III Honorius Tertius', '18 de julho de 1216 a 18 de março de 1227', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (178, 'Gregório IX Gregorius Nonus', '19 de março de 1227 a 22 de agosto de 1241', 'Anagni, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (179, 'Celestino IV, O.Cist. Coelestinus Quartus', '25 de outubro de 1241 a 10 de novembro de 1241', 'Milão, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (180, 'Inocêncio IV Innocentius Quartus', '25 de junho de 1243 a 7 de dezembro de 1254', 'Génova, República de Génova');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (181, 'Alexandre IV Alexander Quartus', '12 de dezembro de 1254 a 25 de maio de 1261', 'Anagni, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (182, 'Urbano IV Urbanus Quartus', '29 de agosto de 1261 a 2 de outubro de 1264', 'Troyes, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (183, 'Clemente IV Clemens Quartus', '5 de fevereiro de 1265 a 29 de dezembro de 1268', 'Saint-Gilles, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (184, 'Gregório X, O.Cist. Gregorius Decimus', '1 de setembro de 1271 a 10 de janeiro de 1276', 'Placência, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (185, 'Inocêncio V, O.P. Innocentius Quintus', '21 de janeiro de 1276 a 22 de junho de 1276', 'Saboia, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (186, 'Adriano V Hadrianus Quintus', '11 de julho de 1276 a 18 de agosto de 1276', 'Génova, República de Génova');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (187, 'João XXI Ioannes Vicesimus Primus', '20 de setembro de 1276 a 20 de maio de 1277', 'Lisboa, Portugal');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (188, 'Nicolau III, O.S.B. Nicolaus Tertius', '25 de novembro de 1277 a 22 de agosto de 1280', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (189, 'Martinho IV Martinus Quartus', '22 de fevereiro de 1281 a 28 de março de 1285', 'Meinpicien, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (190, 'Honório IV Honorius Quartus', '2 de abril de 1285 a 3 de abril de 1287', 'Roma, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (191, 'Nicolau IV, O.F.M. Nicolaus Quartus', '22 de fevereiro de 1288 a 4 de abril de 1292', 'Lisciano Niccone, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (192, 'Celestino V, O.S.B. Cel. Coelestinus Quintus', '5 de julho de 1294 a 13 de dezembro de 1294', 'Sant''Angelo Limosano, Reino da Sicília');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (193, 'Bonifácio VIII Bonifacius Octavus', '24 de dezembro de 1294 a 11 de outubro de 1303', 'Anagni, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (194, 'Bento XI, O.P. Benedictus Undecimus', '22 de outubro de 1303 a 7 de julho de 1304', 'Treviso, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (195, 'Clemente V Clemens Quintus', '5 de junho de 1305 a 20 de abril de 1314', 'Villandraut, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (196, 'João XXII Ioannes Vicesimus Secundus', '7 de agosto de 1316 a 4 de dezembro de 1334', 'Cahors, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (197, 'Bento XII, O.Cist. Benedictus Duodecimus', '20 de dezembro de 1334 a 25 de abril de 1342', 'Saverdun, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (198, 'Clemente VI, O.S.B. Clemens Sextus', '7 de maio de 1342 a 6 de dezembro de 1352', 'Maumont, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (199, 'Inocêncio VI Innocentius Sextus', '18 de dezembro de 1352 a 12 de setembro de 1362', 'Les Monts, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (200, 'Urbano V, O.S.B. Urbanus Quintus', '28 de setembro de 1362 a 19 de dezembro de 1370', 'Grizac, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (201, 'Gregório XI Gregorius Undecimus', '30 de dezembro de 1370 a 26 de março de 1378', 'Maumont, França');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (202, 'Urbano VI Urbanus Sextus', '8 de abril de 1378 a 15 de outubro de 1389', 'Nápoles, Reino de Nápoles');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (203, 'Bonifácio IX Bonifacius Nonus', '2 de novembro de 1389 a 1 de outubro de 1404', 'Nápoles, Reino de Nápoles');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (204, 'Inocêncio VII Innocentius Septimus', '17 de outubro de 1404 a 6 de novembro de 1406', 'Sulmona, Reino de Nápoles');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (205, 'Gregório XII Gregorius Duodecimus', '30 de novembro de 1406 a 4 de julho de 1415', 'Veneza, República de Veneza');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (206, 'Martinho V Martinus Quintus', '11 de novembro de 1417 a 20 de fevereiro de 1431', 'Genazzano, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (207, 'Eugénio IV, O.S.B. Cel. Eugenius Quartus', '3 de março de 1431 a 23 de fevereiro de 1447', 'Veneza, República de Veneza');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (208, 'Nicolau V, O.P. Nicolaus Quintus', '6 de março de 1447 a 24 de março de 1455', 'Sarzana, República de Génova');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (209, 'Calisto III Callistus Tertius', '8 de abril de 1455 a 6 de agosto de 1458', 'Xátiva, Reino de Aragão');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (210, 'Pio II Pius Secundus', '19 de agosto de 1458 a 15 de agosto de 1464', 'Corsignano, República de Siena');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (211, 'Paulo II Paulus Secundus', '30 de agosto de 1464 a 26 de julho de 1471', 'Veneza, República de Veneza');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (212, 'Sisto IV, O.F.M. Xystus Quartus', '9 de agosto de 1471 a 12 de agosto de 1484', 'Celle Ligure, República de Génova');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (213, 'Inocêncio VIII Innocentius Octavus', '29 de agosto de 1484 a 25 de julho de 1492', 'Génova, República de Génova');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (214, 'Alexandre VI Alexander Sextus', '11 de agosto de 1492 a 18 de agosto de 1503', 'Xátiva, Reino de Aragão');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (215, 'Pio III Pius Tertius', '22 de setembro de 1503 a 18 de outubro de 1503', 'Corsignano, República de Siena');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (216, 'Júlio II, O.F.M. Iulius Secundus', '31 de outubro de 1503 a 21 de fevereiro de 1513', 'Albisola, República de Génova');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (217, 'Leão X Leo Decimus', '9 de março de 1513 a 1 de dezembro de 1521', 'Florença, República de Florença');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (218, 'Adriano VI Hadrianus Sextus', '9 de janeiro de 1522 a 14 de setembro de 1523', 'Utrecht, Sacro Império Romano');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (219, 'Clemente VII Clemens Septimus', '26 de novembro de 1523 a 25 de setembro de 1534', 'Florença, República de Florença');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (220, 'Paulo III Paulus Tertius', '12 de outubro de 1534 a 10 de novembro de 1549', 'Canino, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (221, 'Júlio III Iulius Tertius', '29 de novembro de 1549 a 29 de março de 1555', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (222, 'Marcelo II Marcellus Secundus', '9 de abril de 1555 a 1 de maio de 1555', 'Montefano, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (223, 'Paulo IV, C.R. Paulus Quartus', '23 de maio de 1555 a 18 de agosto de 1559', 'Capriglia Irpina, Reino de Nápoles');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (224, 'Pio IV Pius Quartus', '26 de dezembro de 1559 a 9 de dezembro de 1565', 'Milão, Ducado de Milão');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (225, 'Pio V, O.P. Pius Quintus', '7 de janeiro de 1566 a 1 de maio de 1572', 'Bosco, Ducado de Milão');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (226, 'Gregório XIII Gregorius Tertius Decimus', '13 de maio de 1572 a 10 de abril de 1585', 'Bolonha, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (227, 'Sisto V, O.F.M.Conv. Xystus Quintus', '24 de abril de 1585 a 27 de agosto de 1590', 'Grottammare, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (228, 'Urbano VII Urbanus Septimus', '15 de setembro de 1590 a 27 de setembro de 1590', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (229, 'Gregório XIV Gregorius Quartus Decimus', '5 de dezembro de 1590 a 16 de outubro de 1591', 'Somma Lombardo, Ducado de Milão');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (230, 'Inocêncio IX Innocentius Nonus', '29 de outubro de 1591 a 30 de dezembro de 1591', 'Bolonha, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (231, 'Clemente VIII Clemens Octavus', '30 de janeiro de 1592 a 3 de março de 1605', 'Fano, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (232, 'Leão XI Leo Undecimus', '1 de abril de 1605 a 27 de abril de 1605', 'Florença, República de Florença');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (233, 'Paulo V Paulus Quintus', '16 de maio de 1605 a 28 de janeiro de 1621', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (234, 'Gregório XV Gregorius Quintus Decimus', '9 de fevereiro de 1621 a 8 de julho de 1623', 'Bolonha, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (235, 'Urbano VIII Urbanus Octavus', '6 de agosto de 1623 a 29 de julho de 1644', 'Florença, Grão-ducado de Toscana');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (236, 'Inocêncio X Innocentius Decimus', '15 de setembro de 1644 a 7 de janeiro de 1655', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (237, 'Alexandre VII Alexander Septimus', '7 de abril de 1655 a 22 de maio de 1667', 'Siena, Grão-ducado de Toscana');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (238, 'Clemente IX Clemens Nonus', '20 de junho de 1667 a 9 de dezembro de 1669', 'Pistoia, Grão-ducado de Toscana');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (239, 'Clemente X Clemens Decimus', '29 de abril de 1670 a 22 de julho de 1676', 'Roma, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (240, 'Inocêncio XI Innocentius Undecimus', '21 de setembro de 1676 a 12 de agosto de 1689', 'Como, Ducado de Milão');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (241, 'Alexandre VIII Alexander Octavus', '6 de outubro de 1689 a 1 de fevereiro de 1691', 'Veneza, República de Veneza');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (242, 'Inocêncio XII Innocentius Duodecimus', '12 de julho de 1691 a 27 de setembro de 1700', 'Spinazzola, Reino de Nápoles');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (243, 'Clemente XI Clemens Undecimus', '23 de novembro de 1700 a 19 de março de 1721', 'Urbino, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (244, 'Inocêncio XIII Innocentius Tertius Decimus', '8 de maio de 1721 a 7 de março de 1724', 'Poli, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (245, 'Bento XIII, O.P. Benedictus Tertius Decimus', '29 de maio de 1724 a 21 de fevereiro de 1730', 'Gravina in Puglia, Reino de Nápoles');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (246, 'Clemente XII Clemens Duodecimus', '12 de julho de 1730 a 6 de fevereiro de 1740', 'Florença, Grão-ducado de Toscana');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (247, 'Bento XIV Benedictus Decimus Quartus', '17 de agosto de 1740 a 3 de maio de 1758', 'Bolonha, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (248, 'Clemente XIII Clemens Decimus Tertius', '6 de julho de 1758 a 2 de fevereiro de 1769', 'Veneza, República de Veneza');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (249, 'Clemente XIV, O.F.M.Conv. Clemens Decimus Quartus', '19 de maio de 1769 a 22 de setembro de 1774', 'Santarcangelo di Romagna, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (250, 'Pio VI Pius Sextus', '15 de fevereiro de 1775 a 29 de agosto de 1799', 'Cesena, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (251, 'Pio VII, O.S.B. Pius Septimus', '14 de março de 1800 a 20 de agosto de 1823', 'Cesena, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (252, 'Leão XII Leo Duodecimus', '28 de setembro de 1823 a 10 de fevereiro de 1829', 'Genga ou Espoleto, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (253, 'Pio VIII Pius Octavus', '31 de março de 1829 a 1 de dezembro de 1830', 'Cingoli, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (254, 'Gregório XVI, O.S.B.Cam. Gregorius Decimus Sextus', '2 de fevereiro de 1831 a 1 de junho de 1846', 'Belluno, República de Veneza');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (255, 'Pio IX, O.F.S. Pius Nonus', '16 de junho de 1846 a 7 de fevereiro de 1878', 'Senigália, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (256, 'Leão XIII, O.F.S. Leo Decimus Tertius', '20 de fevereiro de 1878 a 20 de julho de 1903', 'Carpineto Romano, Estados Papais');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (257, 'Pio X, O.F.S. Pius Decimus', '4 de agosto de 1903 a 20 de agosto de 1914', 'Riese, Áustria');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (258, 'Bento XV, O.F.S. Beneditus Decimus Quintus', '3 de setembro de 1914 a 22 de janeiro de 1922', 'Génova, Reino da Sardenha');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (259, 'Pio XI, O.F.S. Pius Undecimus', '6 de fevereiro de 1922 a 10 de fevereiro de 1939', 'Desio, Itália');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (260, 'Pio XII, O.P. Pius Duodecimus', '2 de março de 1939 a 9 de outubro de 1958', 'Roma, Itália');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (261, 'João XXIII, O.F.S. Ioannes Vicesimus Tertius', '28 de outubro de 1958 a 3 de junho de 1963', 'Sotto il Monte, Itália');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (262, 'Paulo VI Paulus Sextus', '21 de junho de 1963 a 6 de agosto de 1978', 'Concesio, Itália');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (263, 'João Paulo I Ioannes Paulus Primus', '26 de agosto de 1978 a 28 de setembro de 1978', 'Forno di Canale, Itália');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (264, 'João Paulo II Ioannes Paulus Secundus', '16 de outubro de 1978 a 2 de abril de 2005', 'Wadowice, Polônia');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (265, 'Bento XVI Benedictus Decimus Sextus', '19 de abril de 2005 a 28 de fevereiro de 2013', 'Marktl, Alemanha');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (266, 'Francisco, S.J. Franciscus', '13 de março de 2013 a 21 de abril de 2025', 'Buenos Aires, Argentina');
INSERT INTO popes (id, name, pontificate, place_of_birth) VALUES (267, 'Francisco, S.J. Franciscus', '08 de maio de 2025 a atualidade', 'Chicago, Estados Unidos');