version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_papas
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: papas_db
      MYSQL_USER: papas_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - papas_network

volumes:
  mysql_data:
    driver: local

networks:
  papas_network:
    driver: bridge
